# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test123():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_123(self):
    # Test name: 123
    # Step # | name | target | value
    # 1 | open | https://www.google.com/ | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1920x1040 | 
    self.driver.set_window_size(1920, 1040)
    # 3 | click | name=q | 
    self.driver.find_element(By.NAME, "q").click()
    # 4 | type | name=q | youtube
    self.driver.find_element(By.NAME, "q").send_keys("youtube")
    # 5 | sendKeys | name=q | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)

    time.sleep(3)
    # 6 | mouseOver | css=.eKjLze .LC20lb | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | click | css=.eKjLze .LC20lb | 
    self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb").click()

    time.sleep(5)
    # 9 | click | name=search_query | 
    self.driver.find_element(By.NAME, "search_query").click()
    # 10 | type | name=search_query | hello
    self.driver.find_element(By.NAME, "search_query").send_keys("hello")
    # 11 | sendKeys | name=search_query | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
  
